version: 2.1

jobs:
  test:
    docker:
      - image: elixir:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
            - v1-mix-cache-
      - run:
          name: Install dependencies
          command: mix deps.get
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
      - run:
          name: Compile
          command: mix compile --warnings-as-errors
      - run:
          name: Run tests
          command: mix test

workflows:
  test:
    jobs:
      - test
